import { Paragraph } from "@/components"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body>
        <div style={{border: '2px solid purple'}}><Paragraph>Авторизация</Paragraph></div>
        {children}</body>
    </html>
  )
}
